[project]
name = "open-finance-api"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
    "django-cors-headers>=4.9.0",
    "python-dotenv>=1.2.1",
    "yfinance>=0.2.66",
]
